---

##
## Display a task header only when "_task_header" is defined OR has some content 
- name: "{{ _task_header }}"
  debug:
    msg: ""
  when: (_task_header is defined) and (_task_header | length > 0)
  tags: [print_action]


##
## Unregister a host in Red Hat Satellite
- uri:
    url: "{{ SATELLITE_URL }}/hosts/{{ _vm_name }}"
    user: "{{ _username }}"
    password: "{{ _password }}"
    force_basic_auth: yes
    validate_certs: no
    method: DELETE
    status_code: 200
  register: reg_rhsatellite_unregistration
  failed_when: reg_rhsatellite_unregistration.status not in [200,404]

