---

##
## Display a task header only when "_task_header" is defined OR has some content 
- name: "{{ _task_header }}"
  debug:  
    msg: ""
  when: (_task_header is defined) and (_task_header | length > 0)
  tags: [print_action]


##
## Add a DNS record given "name", "type" and "data" attributes
- uri:
    url: "{{ MM_URL }}/{{ local_uri }}"
    user: "{{ _username }}"
    password: "{{ _password }}"
    force_basic_auth: yes
    validate_certs: no
    method: POST
    body_format: json
    body:
      dnsRecord:
        name: "{{ _record_name }}"
        type: "{{ _record_type }}"
        data: "{{ _record_data }}"
    status_code: 201
  register: reg_new_record_object
  vars:
    local_uri: "DNSZones/{{ NET_DOMAIN }}/DNSRecords"

