---

##
## Display a task header only when "_task_header" is defined OR has some content 
- name: "{{ _task_header }}"
  debug:
    msg: ""
  when: (_task_header is defined) and (_task_header | length > 0)
  tags: [print_action]


##
## Delete a DNS record given the "name" attribute
  uri:
    url: "{{ MM_URL }}/{{ local_uri }}"
    user: "{{ _username }}"
    password: "{{ _password }}"
    force_basic_auth: yes
    validate_certs: no
    method: DELETE
    status_code: 204
  vars:
    local_uri: "/DNSRecords/{{ _record_name }}?objType=DNSRecord"

