---

##
## Display a task header only when "_task_header" is defined OR has some content 
- name: "{{ _task_header }}"
  debug:
    msg: ""
  when: (_task_header is defined) and (_task_header | length > 0)
  tags: [print_action]


##
## Get the gateway IP address from a given network
- uri:
    url: "{{ MM_URL }}/{{ local_uri }}"
    user: "{{ _username }}"
    password: "{{ _password }}"
    force_basic_auth: yes
    validate_certs: no
    method: GET
    status_code: 200
  register: reg_vm_net_gateway
  vars:
    local_uri: "Ranges/{{ _vm_network }}/IPAMRecords?offset=0&limit=1"

